name: mlcc
version: '0.2.1'
summary: MIT Licensed Compiler Collection
license: MIT
description: |
  MIT Licensed Compiler Collection, or mlcc. Written in lua, and designed to use luaJIT for speed.

grade: stable
confinement: classic
base: core20

parts:
  mlcc:
    source: .
    plugin: dump
    stage-packages:
      - luajit


apps:
  mlcc:
    command: usr/bin/luajit $SNAP/lua/core/main.lua SRL:$SNAP
