name: mlcc
version: '0.1.0-dev'
summary: MIT Licensed Compiler Collection
grade: devel
description: |
  MIT Licensed Compiler Collection, or mlcc. Written in lua, and designed to use luaJIT for speed.

confinement: strict

base: core20

parts:
  mlcc:
    source: .
    plugin: dump
    stage-packages:
      - luajit

apps:
  mlcc:
    command: usr/bin/luajit lua/core/main.lua
    plugs:
      - home
